"use client";

/* eslint-disable @next/next/no-img-element -- The QR code is generated by an external QR image endpoint. */

import { useMemo, useState } from "react";
import { CheckCircle2, Clipboard, Loader2, Plane, QrCode } from "lucide-react";
import AppChrome from "@/components/AppChrome";
import { AIRPORTS } from "@/lib/airports";
import type { ServiceType } from "@/lib/bookings";

type IntakeForm = {
  service: ServiceType;
  airport: string;
  pickupAddress: string;
  deliveryAddress: string;
  date: string;
  flightTime: string;
  flight: string;
  bags: number;
  senderName: string;
  senderEmail: string;
  senderPhone: string;
  receiverName: string;
  receiverEmail: string;
  receiverPhone: string;
  notes: string;
  restrictedItemsAttested: boolean;
};

type CreatedBooking = {
  id: string;
  status: string;
  customerAccessToken?: string;
};

const intakeUrl = "https://travelyt.us/intake";
const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=12&data=${encodeURIComponent(
  intakeUrl
)}`;

const emptyForm: IntakeForm = {
  service: "departure",
  airport: "",
  pickupAddress: "",
  deliveryAddress: "",
  date: "",
  flightTime: "",
  flight: "",
  bags: 1,
  senderName: "",
  senderEmail: "",
  senderPhone: "",
  receiverName: "",
  receiverEmail: "",
  receiverPhone: "",
  notes: "",
  restrictedItemsAttested: false,
};

function today() {
  return new Date().toISOString().slice(0, 10);
}

function primaryAddress(form: IntakeForm) {
  if (form.service === "arrival") return form.deliveryAddress.trim();
  if (form.service === "both") {
    return [
      form.pickupAddress.trim() ? `Pickup: ${form.pickupAddress.trim()}` : "",
      form.deliveryAddress.trim() ? `Delivery: ${form.deliveryAddress.trim()}` : "",
    ]
      .filter(Boolean)
      .join(" | ");
  }
  return form.pickupAddress.trim();
}

function structuredNotes(form: IntakeForm) {
  return [
    "QR intake form",
    "",
    "Sender / pickup contact",
    `Name: ${form.senderName.trim()}`,
    `Email: ${form.senderEmail.trim()}`,
    `Phone: ${form.senderPhone.trim() || "(none)"}`,
    `Pickup address: ${form.pickupAddress.trim() || "(none)"}`,
    "",
    "Receiver / delivery contact",
    `Name: ${form.receiverName.trim() || "(none)"}`,
    `Email: ${form.receiverEmail.trim() || "(none)"}`,
    `Phone: ${form.receiverPhone.trim() || "(none)"}`,
    `Delivery address: ${form.deliveryAddress.trim() || "(none)"}`,
    "",
    `Customer notes: ${form.notes.trim() || "(none)"}`,
  ].join("\n");
}

export default function IntakePage() {
  const [form, setForm] = useState<IntakeForm>(emptyForm);
  const [error, setError] = useState("");
  const [created, setCreated] = useState<CreatedBooking | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const summary = useMemo(() => structuredNotes(form), [form]);

  function set<K extends keyof IntakeForm>(key: K, value: IntakeForm[K]) {
    setForm((current) => ({ ...current, [key]: value }));
    setError("");
  }

  async function submit() {
    setSubmitting(true);
    setError("");
    setCreated(null);

    try {
      const response = await fetch("/api/bookings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          service: form.service,
          airport: form.airport,
          address: primaryAddress(form),
          date: form.date,
          flightTime: form.flightTime,
          flight: form.flight.trim() || undefined,
          bags: form.bags,
          name: form.senderName,
          email: form.senderEmail,
          phone: form.senderPhone,
          notes: summary,
          restrictedItemsAttestedAt: form.restrictedItemsAttested
            ? new Date().toISOString()
            : undefined,
          source: "qr-intake",
        }),
      });
      const data = (await response.json()) as {
        ok?: boolean;
        error?: string;
        booking?: CreatedBooking;
      };

      if (!response.ok || !data.booking) {
        throw new Error(data.error || "Could not submit intake.");
      }

      setCreated(data.booking);
      setForm(emptyForm);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not submit intake.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <AppChrome title="Intake" contentWidthClassName="max-w-5xl">
      <div className="space-y-5">
        <div className="grid gap-4 lg:grid-cols-[1fr_240px]">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-navy/55">
              Travelyt intake
            </p>
            <h1 className="mt-1 text-2xl font-bold text-navy">
              Sender and receiver form
            </h1>
          </div>
          <div className="rounded-2xl border border-navy/10 bg-white p-4 text-center shadow-sm shadow-navy/5">
            <img
              src={qrUrl}
              alt="Travelyt intake QR code"
              className="mx-auto h-32 w-32 rounded-xl"
            />
            <div className="mt-3 flex items-center justify-center gap-2 text-xs font-semibold text-navy">
              <QrCode className="h-4 w-4" strokeWidth={2} />
              {intakeUrl.replace("https://", "")}
            </div>
          </div>
        </div>

        {created && (
          <div className="rounded-2xl border border-green-100 bg-green-50 p-4 text-green-800">
            <div className="flex items-center gap-2 font-bold">
              <CheckCircle2 className="h-5 w-5" strokeWidth={2} />
              Intake submitted
            </div>
            <p className="mt-1 text-sm">
              Booking {created.id} is now pending in admin.
            </p>
          </div>
        )}

        {error && (
          <div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">
            {error}
          </div>
        )}

        <form
          onSubmit={(event) => {
            event.preventDefault();
            void submit();
          }}
          className="grid gap-5"
        >
          <section className="rounded-2xl bg-white p-5 shadow-sm shadow-navy/5">
            <div className="mb-4 flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-navy/60">
              <Plane className="h-4 w-4" strokeWidth={2} />
              Trip
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Service
                <select
                  value={form.service}
                  onChange={(event) =>
                    set("service", event.target.value as ServiceType)
                  }
                  className="rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                >
                  <option value="departure">Departure pickup</option>
                  <option value="arrival">Arrival delivery</option>
                  <option value="both">Round trip</option>
                </select>
              </label>
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Airport
                <select
                  required
                  value={form.airport}
                  onChange={(event) => set("airport", event.target.value)}
                  className="rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                >
                  <option value="">Select airport</option>
                  {AIRPORTS.map((airport) => (
                    <option key={airport.code} value={airport.code}>
                      {airport.code} - {airport.name}
                    </option>
                  ))}
                </select>
              </label>
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Travel date
                <input
                  required
                  type="date"
                  min={today()}
                  value={form.date}
                  onChange={(event) => set("date", event.target.value)}
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </label>
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Flight time
                <input
                  required
                  type="time"
                  value={form.flightTime}
                  onChange={(event) => set("flightTime", event.target.value)}
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </label>
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Flight
                <input
                  value={form.flight}
                  onChange={(event) => set("flight", event.target.value)}
                  placeholder="AA 1234"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </label>
              <label className="grid gap-1.5 text-sm font-semibold text-navy">
                Bags
                <input
                  required
                  type="number"
                  min={1}
                  max={20}
                  value={form.bags}
                  onChange={(event) => set("bags", Number(event.target.value))}
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </label>
            </div>
          </section>

          <section className="grid gap-5 lg:grid-cols-2">
            <div className="rounded-2xl bg-white p-5 shadow-sm shadow-navy/5">
              <h2 className="mb-4 text-sm font-bold uppercase tracking-wider text-navy/60">
                Sender
              </h2>
              <div className="grid gap-3">
                <input
                  required
                  value={form.senderName}
                  onChange={(event) => set("senderName", event.target.value)}
                  placeholder="Full name"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <input
                  required
                  type="email"
                  value={form.senderEmail}
                  onChange={(event) => set("senderEmail", event.target.value)}
                  placeholder="Email"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <input
                  value={form.senderPhone}
                  onChange={(event) => set("senderPhone", event.target.value)}
                  placeholder="Phone"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <textarea
                  required={form.service !== "arrival"}
                  value={form.pickupAddress}
                  onChange={(event) => set("pickupAddress", event.target.value)}
                  placeholder="Pickup address"
                  rows={4}
                  className="resize-none rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </div>
            </div>

            <div className="rounded-2xl bg-white p-5 shadow-sm shadow-navy/5">
              <h2 className="mb-4 text-sm font-bold uppercase tracking-wider text-navy/60">
                Receiver
              </h2>
              <div className="grid gap-3">
                <input
                  value={form.receiverName}
                  onChange={(event) => set("receiverName", event.target.value)}
                  placeholder="Full name"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <input
                  type="email"
                  value={form.receiverEmail}
                  onChange={(event) => set("receiverEmail", event.target.value)}
                  placeholder="Email"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <input
                  value={form.receiverPhone}
                  onChange={(event) => set("receiverPhone", event.target.value)}
                  placeholder="Phone"
                  className="rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
                <textarea
                  required={form.service !== "departure"}
                  value={form.deliveryAddress}
                  onChange={(event) => set("deliveryAddress", event.target.value)}
                  placeholder="Delivery address"
                  rows={4}
                  className="resize-none rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
                />
              </div>
            </div>
          </section>

          <section className="rounded-2xl bg-white p-5 shadow-sm shadow-navy/5">
            <label className="grid gap-1.5 text-sm font-semibold text-navy">
              Notes
              <textarea
                value={form.notes}
                onChange={(event) => set("notes", event.target.value)}
                placeholder="Bag details, timing, building access, handoff notes"
                rows={4}
                className="resize-none rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-[#ff6868] focus:ring-2 focus:ring-[#ff6868]/10"
              />
            </label>
            <label className="mt-4 flex gap-3 rounded-xl border border-navy/10 bg-navy/5 p-3 text-sm text-navy">
              <input
                required
                type="checkbox"
                checked={form.restrictedItemsAttested}
                onChange={(event) =>
                  set("restrictedItemsAttested", event.target.checked)
                }
                className="mt-1"
              />
              <span>
                I confirm these bags do not contain restricted or undeclared
                high-value items.
              </span>
            </label>
          </section>

          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <button
              type="button"
              onClick={() => void navigator.clipboard?.writeText(summary)}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-navy/5 px-4 py-3 text-sm font-bold text-navy transition-colors hover:bg-navy/10"
            >
              <Clipboard className="h-4 w-4" strokeWidth={2} />
              Copy summary
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#ff6868] px-5 py-3 text-sm font-bold text-white transition-opacity hover:opacity-90 disabled:opacity-60"
            >
              {submitting ? (
                <Loader2 className="h-4 w-4 animate-spin" strokeWidth={2} />
              ) : null}
              Submit intake
            </button>
          </div>
        </form>
      </div>
    </AppChrome>
  );
}
